#!/bin/sh -e

unset BIN_MATH
unset NO_AUDIO
cd gtk
make cleaner
make -j8
make clean
make -j8 BIN_MATH=1
cd ..
rm -rf Free42Linux
mkdir Free42Linux
cp gtk/README Free42Linux
cp gtk/free42bin Free42Linux
cp gtk/free42dec Free42Linux
strip Free42Linux/free42bin
strip Free42Linux/free42dec
mkdir -p packages
tar cvfz packages/Free42Linux.tgz Free42Linux
rm -rf Free42Linux
