skins/free42skins/AnthraciteC_small_Yellow
Anthracite Classic Yellow
skins/free42skins/AnthraciteC_small
Anthracite Classic Blue
skins/free42skins/Anthracite_small_Yellow
Anthracite Yellow
skins/free42skins/Anthracite_small
Anthracite Blue
